version: "3"


services:
  server1.zookeeper.lab:
    image: zookeeper
    restart: always
    hostname: server1.zookeeper.lab
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888 server.2=server2.zookeeper.lab:2888:3888 server.3=server3.zookeeper.lab:2888:3888
    networks:
      - zookeeper-net
  server2.zookeeper.lab:
    image: zookeeper
    restart: always
    hostname: server1.zookeeper.lab
    ports:
      - 2182:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server1.zookeeper.lab:2888:3888 server.2=0.0.0.0:2888:3888 server.3=server3.zookeeper.lab:2888:3888
    networks:
      - zookeeper-net
  server3.zookeeper.lab:
    image: zookeeper
    restart: always
    hostname: server3.zookeeper.lab
    ports:
      - 2183:2181
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=server1.zookeeper.lab:2888:3888 server.2=server2.zookeeper.lab:2888:3888 server.3=0.0.0.0:2888:3888
    networks:
      - zookeeper-net
      
networks:
  zookeeper-net:
