version: "3"

services:
  server1.redis.lab:
    image: redis
    ports:
      - 6379:6379
    networks:
      - redis-net
    hostname: server1.redis.lab
  server2.redis.lab:
    image: redis
    ports:
      - 6479:6379
    networks:
      - redis-net
    hostname: server2.redis.lab
    command: redis-server --slaveof server1.redis.lab 6379
    depends_on:
      - server1.redis.lab
  server3.redis.lab:
    image: redis
    ports:
      - 6579:6379
    networks:
      - redis-net
    hostname: server3.redis.lab
    command: redis-server --slaveof server1.redis.lab 6379
    depends_on:
      - server1.redis.lab
  sentinel1.redis.lab:
    image: redis
    volumes:
      - ./sentinel.conf:/data/sentinel.conf
    command: redis-server /data/sentinel.conf --sentinel
    hostname: sentinel1.redis.lab
    depends_on:
      - server1.redis.lab
    networks:
      - redis-net
  sentinel2.redis.lab:
    image: redis
    volumes:
      - ./sentinel.conf:/data/sentinel.conf
    command: redis-server /data/sentinel.conf --sentinel
    hostname: sentinel2.redis.lab
    depends_on:
      - server1.redis.lab
    networks:
      - redis-net
  sentinel3.redis.lab:
    image: redis
    volumes:
      - ./sentinel.conf:/data/sentinel.conf
    command: redis-server /data/sentinel.conf --sentinel
    hostname: sentinel3.redis.lab
    depends_on:
      - server1.redis.lab
    networks:
      - redis-net
networks:
  redis-net:
