version: "3"
services:
  #config server
  config01.mongo.lab:
    container_name: config01.mongo.lab
    image: mongo
    ports:
      - 27017:27017
    networks:
      - mongo-net
    command:
      --configsvr --replSet mongo-config-set --port 27017
    hostname: config01.mongo.lab
  config02.mongo.lab:
    container_name: config02.mongo.lab
    image: mongo
    ports:
      - 27018:27017
    networks:
      - mongo-net
    command:
      --configsvr --replSet mongo-config-set --port 27017
    hostname: config02.mongo.lab
  config03.mongo.lab:
    container_name: config03.mongo.lab
    image: mongo
    ports:
      - 27019:27017
    networks:
      - mongo-net
    command:
      --configsvr --replSet mongo-config-set --port 27017
    hostname: config03.mongo.lab
  #shard 1
  shard01a.mongo.lab:
    container_name: shard01a.mongo.lab
    image: mongo
    ports:
      - 37017:27017
    networks:
      - mongo-net
    command:
      --replSet mongo-shard-set-01
    hostname: shard01a.mongo.lab
  shard01b.mongo.lab:
    container_name: shard01b.mongo.lab
    image: mongo
    ports:
      - 37018:27017
    networks:
      - mongo-net
    command:
      --replSet mongo-shard-set-01
    hostname: shard01b.mongo.lab
  shard01c.mongo.lab:
    container_name: shard01c.mongo.lab
    image: mongo
    ports:
      - 37019:27017
    networks:
      - mongo-net
    command:
      --replSet mongo-shard-set-01
    hostname: shard01c.mongo.lab

  #shard 2
  shard02a.mongo.lab:
    container_name: shard02a.mongo.lab
    image: mongo
    ports:
      - 47017:27017
    networks:
      - mongo-net
    command:
      --replSet mongo-shard-set-02
    hostname: shard02a.mongo.lab
  shard02b.mongo.lab:
    container_name: shard02b.mongo.lab
    image: mongo
    ports:
      - 47018:27017
    networks:
      - mongo-net
    command:
      --replSet mongo-shard-set-02
    hostname: shard02b.mongo.lab
  shard02c.mongo.lab:
    container_name: shard02c.mongo.lab
    image: mongo
    ports:
      - 47019:27017
    networks:
      - mongo-net
    command:
      --replSet mongo-shard-set-02
    hostname: shard02c.mongo.lab

  #router
  router.mongo.lab:
    container_name: router.mongo.lab
    image: mongo
    ports:
      - 57018:27017
    networks:
      - mongo-net
    command:
      mongos --configdb  mongo-config-set/config01.mongo.lab:27017,config02.mongo.lab:27017,config03.mongo.lab:27017 --port 27017
    hostname: router.mongo.lab
networks:
  mongo-net:
