version: "3"


services:
  zookeeper1.kafka.lab:
    image: zookeeper
    restart: always
    hostname: zookeeper1.kafka.lab
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888 server.2=zookeeper2.kafka.lab:2888:3888 server.3=zookeeper3.kafka.lab:2888:3888
    networks:
      - kafka-net
  zookeeper2.kafka.lab:
    image: zookeeper
    restart: always
    hostname: zookeeper2.kafka.lab
    ports:
      - 2182:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zookeeper1.kafka.lab:2888:3888 server.2=0.0.0.0:2888:3888 server.3=zookeeper3.kafka.lab:2888:3888
    networks:
      - kafka-net
  zookeeper3.kafka.lab:
    image: zookeeper
    restart: always
    hostname: zookeeper3.kafka.lab
    ports:
      - 2183:2181
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zookeeper1.kafka.lab:2888:3888 server.2=zookeeper2.kafka.lab:2888:3888 server.3=0.0.0.0:2888:3888
    networks:
      - kafka-net
  server1.kafka.lab:
    build: .
    hostname: server1.kafka.lab
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1.kafka.lab:2181
    networks:
      - kafka-net
  manager.kafka.lab:
    image: intropro/kafka-manager
    container_name: manager.kafka.lab
    hostname: manager.kafka.lab
    ports:
        - "9009:9000"
    environment:
        ZK_HOSTS: zookeeper1.kafka.lab:2181
    networks:
      - kafka-net

networks:
  kafka-net:
